# Generated by Django 3.2.5 on 2021-07-03 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movement_pass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('id_number', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='user-registraion/')),
                ('is_admin', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.district')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.gender')),
                ('id_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.idtype')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
