# Generated by Django 3.2.5 on 2021-07-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movement_pass', '0003_applypass_movementreason_movementtype_timelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_from', models.CharField(max_length=50)),
                ('where_to', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('journey_date', models.DateTimeField()),
                ('qr_image', models.ImageField(upload_to='qr/')),
                ('applied_date', models.DateField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.district')),
                ('movement_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.movementreason')),
                ('movement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.movementtype')),
                ('passuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('time_limit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement_pass.timelimit')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplyPass',
        ),
    ]
