# Generated by Django 3.2.5 on 2021-07-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement_pass', '0004_auto_20210705_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_pass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apply_pass',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
