# Generated by Django 3.2.5 on 2021-07-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement_pass', '0005_auto_20210707_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_pass',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
